# Determines how the plugin will count days
# - gametime - uses total ticks since world creation
# - fulltime - uses world.getFullTime()
# Option gametime is default.
counter-mode: gametime

# Update interval in ticks (20 ticks = 1 second).
update-interval: 1200

# Boss bar/progress bar color. Has optional phase colors.
bossbar:
  # Default single color
  defaultColor: WHITE

  # dawnColor: RED
  # dayColor: YELLOW
  # duskColor: BLUE
  # nightColor: PURPLE

config-version: 1
