name: TakeYourTime
main: me.yiliya.takeYourTime.TakeYourTime
version: '1.0'
api-version: '1.21'
author: Yiliya
description: A Minecraft plugin that adds a customizable in-game clock with bossbar/actionbar support.

commands:
  clock:
    description: Toggle or configure the in-game clock
    usage: |
      /clock on - Enable the clock display
      /clock off - Disable the clock display
      /clock mode <actionbar|bossbar> - Change display mode

  takeyourtime:
    description: Show information about the TakeYourTime plugin
    usage: /<command>
    aliases: [tyt]
