name: TakeYourTime
main: me.yiliya.takeYourTime.TakeYourTime
version: '1.0'
api-version: '1.21'
author: Yiliya
description: A Minecraft plugin that adds a customizable in-game clock with bossbar/actionbar support.

commands:
  clock:
    description: Toggle or configure the in-game clock
    usage: /clock <args>
  tyt:
    description: Show information about the TakeYourTime plugin
    usage: /tyt
